name: my_goals
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  built_value: ^6.4.0
  built_collection: ^4.2.0
  rxdart: ^0.21.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator: ^6.4.0


flutter:
  uses-material-design: true